# frozen_string_literal: true

require "rake"
require "rake/testtask"
require "rubocop/rake_task"

TEST_ROOT = File.expand_path("test", __dir__)

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList[File.join(TEST_ROOT, "**", "*_test.rb")]
  t.verbose = true
end

RuboCop::RakeTask.new(:style) do |t|
  t.options = ["--display-cop-names"]
end

desc "Run RuboCop with autocorrect"
task "style:fix" do
  sh "rubocop -A"
end

desc "Run MarkdownLint"
task "style:mdl" do
  sh "mdl ."
end

desc "Run game"
task "game" do
  ruby "game.rb"
end

task default: %i[test style]
